language: node_js
node_js:
  - '4.2'

env:
  global:
  - secure: E43Ij0IjiQYDzzKKwY2NDxYsTQEMlS7mtqXHAoPsubIJnVI4IcJEfv4QIoH+yO/+izo3B3ozI1BcmwYk1RGriBf/1caObcrqNRMsjCrON2+W7l26qvJJyOA7C5Vf2d2AzBIm8OeRd2Y2aMq8AdFoRI+NRne72eZn0JGSGz+Orfad7bNUIkE7vr24rDJi5tUtey/MZFtCQ/3EQl3BJoyRLJtcfe2yFAyIqZu8n7GYqllWjG89huH7xkXVO9CUR2nSEuUtGuh7BE1jZI1k76D+ouagRUI+5UUh7G1qYu219f4tDJcBDMS2pthW/h/9Dl+ZTNKXp9FwFLbAs4kfk8hJo3wk09NrGGb8/hpkPe4gkX+BAGqs45agoO9Y8gnGhmOUupoDsanvDbKtalK4/CI/rcV2LFunrhCPsIbFeT0mub/18ysfTjJre5hL2SphKljRn5B94yI1mS4vAc6NUW60yaqoM+Aku5tOd6eDm2mzX72+Mf9KU7NSTkiepk+qXRtJIdvZYAHhMk4hjX2uQbt9SLYj/Ni4mGoFjsewszt6mHHeZa7W860hInxLWfv/kF6g5Tf+DYyK4BZFMYSiXQH+yUPB8YofMKSOiROY8kkMgvZbcjNMGkYYu0PrVO4w2wEe+pKQIdKEiVmXQpweMbxB7M/inURzRkNJYs7qUFppSK4=
  - secure: DZwu0sLnLlRzgnBPxKDD0olbZ34vyfdTk7J0+p19hsi6yDsBIYvKnAmx8O3hpESKPNYrqyZgD+EvFcF1iwvNjIGQnG/vF8zx5sgWlnBP1G9njaLxixRTSHgqvO+VWVSs0ZmlFVebxkR/R3NrImkc/gzpmnVmLMAQXhHWef3WgPeljSShloelguEHP4mEcdJVRIIrVV/JzCL1mJDyYaFBo96LFF5T80eu5izqV3knCx1OXM+J/4Yx37JMI/gboJXJQ2MbzPPHImKKwD7rZ0y3rmohX8IHxiOACK0lI8/qPmNWxq+rN4nk5rjkuzKuz8eWOqdzaqEUGcnY2cviNoEsyNF3PGGXNr6HNuOJLWB7C4qlBW/k8sqmBqAYXLqSf9k/YM0wZ6i4vHfMgWQBAN6qYIUPaJKF32LjRL2EjSWGsOzkMokBTnwBkLm4zNq4OTbnWiiwHu3g9oxQIQ4ilvAA9YMslAHwI+FPNWR94Kw8NTRUzAa02PMeapHD9hWkpZoDOY3hX/rF1xPDELv8PiCsDlWZgCKhAC6DTNamo5C2qU8qnWgz94vlNa0k42NgISerRojzk/MXgE93TIQVhOo0AJZLf0uBo84aGFpJ7kj7HdApXxhn75ZfV2srnwidk23k5c9EFJ9lHWM5X5/yrzly+EfJB5EBT8mb8ei6P/IM9QI=
  - secure: FIo9Ya4Ov4OaZqBe1hWZobbKX4QItkGfzPjO1d+V3kpQzanEy/GAQo9Y15VWpmh9LsGVzbHl93zp43nGqXzg7WKs3T9f2AAJNjlEiLay9EYmVtCgE21KizwNvQYBXUn6DcDqgvvTyBJVRGrU+90lP+LtHkrfBwrAk/k8rXywgKxCnVJUJhUdcLgyl+Y8/cgRt+dhpBzthKhbEvWT1T4gPv8hJX59ZqmgFJWaTYC0uu1ovjz3pjZGWTq33SUyps9b6LDkJBryaDYzcmmDDXEh5BGbvSAvyb5kt4qxy4bbLQxofpKBMxL2AwyiPDM8deGmHApQwEj9WydP3HDskYuyJcVv21ra4FWuskVTiYxq9Oms1qDPzb1s5SioA8A9dVc8e04GV0vKJ/6pyDxQK2kcAnGtbL09S7B1oFvxncWIzgWLTkDfeFl+GXg6Wo9OofUd4APQV5v/WSg+zLR+3AoJw6VRy6sA8RYjuWn34VtrFY5eVjVfZnERhcqviqCMzPjDC97sxDGKYB/UF/Yp9tnXZrj7FukI73I9unnKegE9dECUC7sYISnXaEshjntejQgAQAZzzW26Cyuq5FdH5rxYEOvYjoGB+H0Ix3c3DplmIHZGf71/i75nvOcsr6SLCwn3ZJWzWL5Tq3pX/w2ThvWm/FyExb+S33i1xzWA0th3FAI=

before_deploy:
  - sudo pip install awscli

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    tags: true
